name:                wyag
version:             0.1.0.0
github:              "rethab/wyag"
license:             MIT
author:              "Reto Habluetzel"
maintainer:          "rethab@pm.me"
copyright:           "2019 Reto Habluetzel"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rethab/wyag#readme>

dependencies:
- base >= 4.7 && < 5
- text
- cmdargs
- directory
- filepath
- ini
- unordered-containers
- transformers

library:
  source-dirs: src

executables:
  wyag-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wyag

tests:
  wyag-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wyag
